version: "3.2"
services:
  db_mysql:
    image: mariadb:10.3.2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: volume
        target: /var/lib/mysql
        source: clip_db
  clip_management:
    image: zigakern/clip_management:v0.1.5
    ports:
      - 8081:8081
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:mysql://db_mysql:3306/clips
      - KUMULUZEE_SERVER_BASE-URL=http://192.168.99.100:8081
      #- REST-PROPERTIES_EXTERNAL-DEPENDENCIES_CLIP-SERVICE_WRITE-ENABLED=0
    depends_on:
      - db_mysql

volumes:
    clip_db: