apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-4
  labels:
    type: local
    app: clip-management
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-4
  storageClassName: standard
