kumuluzee:
  name: clip_management
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ClipsDB
      connection-url: jdbc:mysql://192.168.99.100:3306/clips
      username: root
      password: root
      max-pool-size: 20
rest-properties:
  external-dependencies:
    order-service:
      enabled: true