kumuluzee:
  name: clip_management
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/ClipsDB
      connection-url: jdbc:mysql://192.168.99.100:3306/clips
      username: root
      password: root
      max-pool-size: 20
  config:
      etcd:
        hosts: http://192.168.99.100:2379
  discovery:
      etcd:
        hosts: http://192.168.99.100:2379
rest-properties:
  external-dependencies:
    clip-service:
      write-enabled: true